# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Amb
version:      0.02
version_from: Amb.pm
installdirs:  site
requires:
    B::Generate:                   1.13
    PadWalker:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
